1. Setup

In [1]:
from src.bronze.pipeline import BronzePipeline

pipeline = BronzePipeline()
spark = pipeline.spark

26/06/23 20:13:15 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).

----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 52160)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/lib/python3.8/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.8/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/local/lib/python3.8/site-packages/pyspark/accumulators.py", line 295, in handle
    poll(accum_updates)
  File "/usr/local/lib/python3.8/site-packages/pyspark/accumulators.py", line 267, in poll
    if self.rfile in r and func():
  File "/usr/local/lib/python3.8/site-packages/pyspark/accumulators.py", line 271, in accum_updates
    num_updates = read_int(self.rfile)
  File "/usr/local/lib/python3.8/site-packages/pyspark/serializers.py", line 596, in read_int
    raise EOFError
EOFError
----------------------------------------

2. CSV

In [2]:
csv_output_path = pipeline.run(
    source_path="/app/data/raw_local/RAW/2024-07-13_0800/CONTROLE DE MEDICOES E PAGAMENTOS/ControleMedicoesPagamentos.csv",
    source_type="csv",
    dataset_name="controle_medicoes_pagamentos",
    snapshot_date="2024-07-13_0800",
    source_file="ControleMedicoesPagamentos.csv",
    file_hash="manual_test_hash"
)

print(csv_output_path)
spark.read.parquet(csv_output_path).select("_snapshot_date", "_source_file", "_source_type").show(5)

26/06/23 20:13:20 WARN MetricsConfig: Cannot locate configuration: tried hadoop-metrics2-s3a-file-system.properties,hadoop-metrics2.properties
26/06/23 20:13:22 WARN SparkStringUtils: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.

s3a://contracts/bronze/source_type=csv/dataset=controle_medicoes_pagamentos/snapshot_date=2024-07-13_0800/
+---------------+--------------------+------------+
| _snapshot_date|        _source_file|_source_type|
+---------------+--------------------+------------+
|2024-07-13_0800|ControleMedicoesP...|         csv|
|2024-07-13_0800|ControleMedicoesP...|         csv|
|2024-07-13_0800|ControleMedicoesP...|         csv|
|2024-07-13_0800|ControleMedicoesP...|         csv|
|2024-07-13_0800|ControleMedicoesP...|         csv|
+---------------+--------------------+------------+
only showing top 5 rows

3. XLSX

In [3]:
xlsx_output_path = pipeline.run(
    source_path="/app/data/raw_local/RAW/2024-07-13_0800/CONTROLE DE MEDICOES EM ANDAMENTO/Exportação_bm_acompanhamento.xlsx",
    source_type="xlsx",
    dataset_name="controle_medicoes_andamento",
    snapshot_date="2024-07-13_0800",
    source_file="Exportação_bm_acompanhamento.xlsx",
    file_hash="manual_test_hash"
)

print(xlsx_output_path)
spark.read.parquet(xlsx_output_path).select("_snapshot_date", "_source_file", "_source_type").show(5)

s3a://contracts/bronze/source_type=xlsx/dataset=controle_medicoes_andamento/snapshot_date=2024-07-13_0800/
+---------------+--------------------+------------+
| _snapshot_date|        _source_file|_source_type|
+---------------+--------------------+------------+
|2024-07-13_0800|Exportação_bm_aco...|        xlsx|
|2024-07-13_0800|Exportação_bm_aco...|        xlsx|
|2024-07-13_0800|Exportação_bm_aco...|        xlsx|
|2024-07-13_0800|Exportação_bm_aco...|        xlsx|
|2024-07-13_0800|Exportação_bm_aco...|        xlsx|
+---------------+--------------------+------------+
only showing top 5 rows

4. XLSB / NACT

In [4]:
xlsb_output_path = pipeline.run(
    source_path="/app/data/raw_local/RAW/2024-07-13_0800/NACT/202211_ADMIN.xlsb",
    source_type="xlsb",
    dataset_name="nact",
    snapshot_date="2024-07-13_0800",
    source_file="202211_ADMIN.xlsb",
    file_hash="manual_test_hash"
)

print(xlsb_output_path)
spark.read.parquet(xlsb_output_path).select("_snapshot_date", "_source_file", "_source_type").show(5)

26/06/23 20:13:45 WARN TaskSetManager: Stage 6 contains a task of very large size (1043 KiB). The maximum recommended task size is 1000 KiB.

s3a://contracts/bronze/source_type=xlsb/dataset=nact/snapshot_date=2024-07-13_0800/
+---------------+-----------------+------------+
| _snapshot_date|     _source_file|_source_type|
+---------------+-----------------+------------+
|2024-07-13_0800|202211_ADMIN.xlsb|        xlsb|
|2024-07-13_0800|202211_ADMIN.xlsb|        xlsb|
|2024-07-13_0800|202211_ADMIN.xlsb|        xlsb|
|2024-07-13_0800|202211_ADMIN.xlsb|        xlsb|
|2024-07-13_0800|202211_ADMIN.xlsb|        xlsb|
+---------------+-----------------+------------+
only showing top 5 rows

5. Sumário

In [5]:
validation_results = {
    "csv": csv_output_path,
    "xlsx": xlsx_output_path,
    "xlsb": xlsb_output_path,
}

validation_results

{'csv': 's3a://contracts/bronze/source_type=csv/dataset=controle_medicoes_pagamentos/snapshot_date=2024-07-13_0800/',
 'xlsx': 's3a://contracts/bronze/source_type=xlsx/dataset=controle_medicoes_andamento/snapshot_date=2024-07-13_0800/',
 'xlsb': 's3a://contracts/bronze/source_type=xlsb/dataset=nact/snapshot_date=2024-07-13_0800/'}

5. Isso libera o worker para o próximo notebook.

In [6]:
#spark.stop()

### Batch Validation

In [ ]:
# 1. Run Bronze Batch
from src.bronze.batch import run_bronze_batch

bronze_batch_df = run_bronze_batch()

bronze_batch_df["status"].value_counts()

status
SUCCESS    1
Name: count, dtype: int64

In [11]:
# 2. Execution Summary
bronze_batch_df[
    [
        "execution_id",
        "source_file",
        "dataset_name",
        "source_type",
        "snapshot_date",
        "status",
        "duration_seconds",
    ]
].head(10)

,execution_id,source_file,dataset_name,source_type,snapshot_date,status,duration_seconds
0,bronze_20260623_223833_e231d174,ControleMedicoesPagamentos.csv,controle_medicoes_pagamentos,csv,2024-07-13_0800,SUCCESS,1.040435

In [12]:
# 3. Failed Records
bronze_batch_df[
    bronze_batch_df["status"] == "FAILED"
][
    [
        "source_file",
        "snapshot_date",
        "dataset_name",
        "error_message",
    ]
]

Empty DataFrame
Columns: [source_file, snapshot_date, dataset_name, error_message]
Index: []

In [ ]:
# Validar o log persistido:
from src.config.settings import Settings
import pandas as pd

pd.read_csv(Settings.BRONZE_EXECUTION_LOG_PATH).head(10)

,execution_id,source_file,dataset_name,status,start_time,end_time,duration_seconds,error_message,snapshot_date,source_type,bronze_path
0,bronze_20260623_223833_e231d174,ControleMedicoesPagamentos.csv,controle_medicoes_pagamentos,SUCCESS,2026-06-23T22:38:33.314808+00:00,2026-06-23T22:38:34.355243+00:00,1.040435,NaN,2024-07-13_0800,csv,s3a://contracts/bronze/source_type=csv/dataset...

### Idempotência
Ex: arquivo processado 10 vezes

Em produção isso é inaceitável.
se file_hash já existe no execution_log
→ não reprocessar